name: ast366foo
channels:
  - astropy
  - conda-forge
dependencies:
- python=3.6
- astropy
- astroquery
- matplotlib<3
- ipython
- jupyter
- ipywidgets
- scipy
- nose
- mock
- funcsigs
- pillow
- ccdproc
- scikit-image
- dask
- wcsaxes
- astroplan
- msumastro
- reducer
- ginga
- reproject
- opencv
- ipyevents
- photutils
- bottleneck
- pip:
  - tqdm
  - glowing-waffles
  - https://github.com/astropy/astrowidgets/archive/master.zip
